import './country.dart';

List<Country> countries = [
new Country(name: "Andorra", isoCode: "AD"),
new Country(name: "United Arab Emirates", isoCode: "AE"),
new Country(name: "Afghanistan", isoCode: "AF"),
new Country(name: "Antigua and Barbuda", isoCode: "AG"),
new Country(name: "Anguilla", isoCode: "AI"),
new Country(name: "Albania", isoCode: "AL"),
new Country(name: "Armenia", isoCode: "AM"),
new Country(name: "Angola", isoCode: "AO"),
new Country(name: "Asia/Pacific Region", isoCode: "AP"),
new Country(name: "Antarctica", isoCode: "AQ"),
new Country(name: "Argentina", isoCode: "AR"),
new Country(name: "American Samoa", isoCode: "AS"),
new Country(name: "Austria", isoCode: "AT"),
new Country(name: "Australia", isoCode: "AU"),
new Country(name: "Aruba", isoCode: "AW"),
new Country(name: "Aland Islands", isoCode: "AX"),
new Country(name: "Azerbaijan", isoCode: "AZ"),
new Country(name: "Bosnia and Herzegovina", isoCode: "BA"),
new Country(name: "Barbados", isoCode: "BB"),
new Country(name: "Bangladesh", isoCode: "BD"),
new Country(name: "Belgium", isoCode: "BE"),
new Country(name: "Burkina Faso", isoCode: "BF"),
new Country(name: "Bulgaria", isoCode: "BG"),
new Country(name: "Bahrain", isoCode: "BH"),
new Country(name: "Burundi", isoCode: "BI"),
new Country(name: "Benin", isoCode: "BJ"),
new Country(name: "Saint Barthelemy", isoCode: "BL"),
new Country(name: "Bermuda", isoCode: "BM"),
new Country(name: "Brunei Darussalam", isoCode: "BN"),
new Country(name: "Bolivia", isoCode: "BO"),
new Country(name: "Bonaire, Saint Eustatius and Saba", isoCode: "BQ"),
new Country(name: "Brazil", isoCode: "BR"),
new Country(name: "Bahamas", isoCode: "BS"),
new Country(name: "Bhutan", isoCode: "BT"),
new Country(name: "Bouvet Island", isoCode: "BV"),
new Country(name: "Botswana", isoCode: "BW"),
new Country(name: "Belarus", isoCode: "BY"),
new Country(name: "Belize", isoCode: "BZ"),
new Country(name: "Canada", isoCode: "CA"),
new Country(name: "Cocos (Keeling) Islands", isoCode: "CC"),
new Country(name: "Congo, The Democratic Republic of the", isoCode: "CD"),
new Country(name: "Central African Republic", isoCode: "CF"),
new Country(name: "Congo", isoCode: "CG"),
new Country(name: "Switzerland", isoCode: "CH"),
new Country(name: "Cote d'Ivoire", isoCode: "CI"),
new Country(name: "Cook Islands", isoCode: "CK"),
new Country(name: "Chile", isoCode: "CL"),
new Country(name: "Cameroon", isoCode: "CM"),
new Country(name: "China", isoCode: "CN"),
new Country(name: "Colombia", isoCode: "CO"),
new Country(name: "Costa Rica", isoCode: "CR"),
new Country(name: "Cuba", isoCode: "CU"),
new Country(name: "Cape Verde", isoCode: "CV"),
new Country(name: "Curacao", isoCode: "CW"),
new Country(name: "Christmas Island", isoCode: "CX"),
new Country(name: "Cyprus", isoCode: "CY"),
new Country(name: "Czech Republic", isoCode: "CZ"),
new Country(name: "Germany", isoCode: "DE"),
new Country(name: "Djibouti", isoCode: "DJ"),
new Country(name: "Denmark", isoCode: "DK"),
new Country(name: "Dominica", isoCode: "DM"),
new Country(name: "Dominican Republic", isoCode: "DO"),
new Country(name: "Algeria", isoCode: "DZ"),
new Country(name: "Ecuador", isoCode: "EC"),
new Country(name: "Estonia", isoCode: "EE"),
new Country(name: "Egypt", isoCode: "EG"),
new Country(name: "Western Sahara", isoCode: "EH"),
new Country(name: "Eritrea", isoCode: "ER"),
new Country(name: "Spain", isoCode: "ES"),
new Country(name: "Ethiopia", isoCode: "ET"),
new Country(name: "Europe", isoCode: "EU"),
new Country(name: "Finland", isoCode: "FI"),
new Country(name: "Fiji", isoCode: "FJ"),
new Country(name: "Falkland Islands (Malvinas)", isoCode: "FK"),
new Country(name: "Micronesia, Federated States of", isoCode: "FM"),
new Country(name: "Faroe Islands", isoCode: "FO"),
new Country(name: "France", isoCode: "FR"),
new Country(name: "Gabon", isoCode: "GA"),
new Country(name: "United Kingdom", isoCode: "GB"),
new Country(name: "Grenada", isoCode: "GD"),
new Country(name: "Georgia", isoCode: "GE"),
new Country(name: "French Guiana", isoCode: "GF"),
new Country(name: "Guernsey", isoCode: "GG"),
new Country(name: "Ghana", isoCode: "GH"),
new Country(name: "Gibraltar", isoCode: "GI"),
new Country(name: "Greenland", isoCode: "GL"),
new Country(name: "Gambia", isoCode: "GM"),
new Country(name: "Guinea", isoCode: "GN"),
new Country(name: "Guadeloupe", isoCode: "GP"),
new Country(name: "Equatorial Guinea", isoCode: "GQ"),
new Country(name: "Greece", isoCode: "GR"),
new Country(name: "South Georgia and the South Sandwich Islands", isoCode: "GS"),
new Country(name: "Guatemala", isoCode: "GT"),
new Country(name: "Guam", isoCode: "GU"),
new Country(name: "Guinea-Bissau", isoCode: "GW"),
new Country(name: "Guyana", isoCode: "GY"),
new Country(name: "Hong Kong", isoCode: "HK"),
new Country(name: "Heard Island and McDonald Islands", isoCode: "HM"),
new Country(name: "Honduras", isoCode: "HN"),
new Country(name: "Croatia", isoCode: "HR"),
new Country(name: "Haiti", isoCode: "HT"),
new Country(name: "Hungary", isoCode: "HU"),
new Country(name: "Indonesia", isoCode: "ID"),
new Country(name: "Ireland", isoCode: "IE"),
new Country(name: "Israel", isoCode: "IL"),
new Country(name: "Isle of Man", isoCode: "IM"),
new Country(name: "India", isoCode: "IN"),
new Country(name: "British Indian Ocean Territory", isoCode: "IO"),
new Country(name: "Iraq", isoCode: "IQ"),
new Country(name: "Iran, Islamic Republic of", isoCode: "IR"),
new Country(name: "Iceland", isoCode: "IS"),
new Country(name: "Italy", isoCode: "IT"),
new Country(name: "Jersey", isoCode: "JE"),
new Country(name: "Jamaica", isoCode: "JM"),
new Country(name: "Jordan", isoCode: "JO"),
new Country(name: "Japan", isoCode: "JP"),
new Country(name: "Kenya", isoCode: "KE"),
new Country(name: "Kyrgyzstan", isoCode: "KG"),
new Country(name: "Cambodia", isoCode: "KH"),
new Country(name: "Kiribati", isoCode: "KI"),
new Country(name: "Comoros", isoCode: "KM"),
new Country(name: "Saint Kitts and Nevis", isoCode: "KN"),
new Country(name: "Korea, Democratic People's Republic of", isoCode: "KP"),
new Country(name: "Korea, Republic of", isoCode: "KR"),
new Country(name: "Kuwait", isoCode: "KW"),
new Country(name: "Cayman Islands", isoCode: "KY"),
new Country(name: "Kazakhstan", isoCode: "KZ"),
new Country(name: "Lao People's Democratic Republic", isoCode: "LA"),
new Country(name: "Lebanon", isoCode: "LB"),
new Country(name: "Saint Lucia", isoCode: "LC"),
new Country(name: "Liechtenstein", isoCode: "LI"),
new Country(name: "Sri Lanka", isoCode: "LK"),
new Country(name: "Liberia", isoCode: "LR"),
new Country(name: "Lesotho", isoCode: "LS"),
new Country(name: "Lithuania", isoCode: "LT"),
new Country(name: "Luxembourg", isoCode: "LU"),
new Country(name: "Latvia", isoCode: "LV"),
new Country(name: "Libyan Arab Jamahiriya", isoCode: "LY"),
new Country(name: "Morocco", isoCode: "MA"),
new Country(name: "Monaco", isoCode: "MC"),
new Country(name: "Moldova, Republic of", isoCode: "MD"),
new Country(name: "Montenegro", isoCode: "ME"),
new Country(name: "Saint Martin", isoCode: "MF"),
new Country(name: "Madagascar", isoCode: "MG"),
new Country(name: "Marshall Islands", isoCode: "MH"),
new Country(name: "Macedonia", isoCode: "MK"),
new Country(name: "Mali", isoCode: "ML"),
new Country(name: "Myanmar", isoCode: "MM"),
new Country(name: "Mongolia", isoCode: "MN"),
new Country(name: "Macao", isoCode: "MO"),
new Country(name: "Northern Mariana Islands", isoCode: "MP"),
new Country(name: "Martinique", isoCode: "MQ"),
new Country(name: "Mauritania", isoCode: "MR"),
new Country(name: "Montserrat", isoCode: "MS"),
new Country(name: "Malta", isoCode: "MT"),
new Country(name: "Mauritius", isoCode: "MU"),
new Country(name: "Maldives", isoCode: "MV"),
new Country(name: "Malawi", isoCode: "MW"),
new Country(name: "Mexico", isoCode: "MX"),
new Country(name: "Malaysia", isoCode: "MY"),
new Country(name: "Mozambique", isoCode: "MZ"),
new Country(name: "Namibia", isoCode: "NA"),
new Country(name: "New Caledonia", isoCode: "NC"),
new Country(name: "Niger", isoCode: "NE"),
new Country(name: "Norfolk Island", isoCode: "NF"),
new Country(name: "Nigeria", isoCode: "NG"),
new Country(name: "Nicaragua", isoCode: "NI"),
new Country(name: "Netherlands", isoCode: "NL"),
new Country(name: "Norway", isoCode: "NO"),
new Country(name: "Nepal", isoCode: "NP"),
new Country(name: "Nauru", isoCode: "NR"),
new Country(name: "Niue", isoCode: "NU"),
new Country(name: "New Zealand", isoCode: "NZ"),
new Country(name: "Oman", isoCode: "OM"),
new Country(name: "Panama", isoCode: "PA"),
new Country(name: "Peru", isoCode: "PE"),
new Country(name: "French Polynesia", isoCode: "PF"),
new Country(name: "Papua New Guinea", isoCode: "PG"),
new Country(name: "Philippines", isoCode: "PH"),
new Country(name: "Pakistan", isoCode: "PK"),
new Country(name: "Poland", isoCode: "PL"),
new Country(name: "Saint Pierre and Miquelon", isoCode: "PM"),
new Country(name: "Pitcairn", isoCode: "PN"),
new Country(name: "Puerto Rico", isoCode: "PR"),
new Country(name: "Palestinian Territory", isoCode: "PS"),
new Country(name: "Portugal", isoCode: "PT"),
new Country(name: "Palau", isoCode: "PW"),
new Country(name: "Paraguay", isoCode: "PY"),
new Country(name: "Qatar", isoCode: "QA"),
new Country(name: "Reunion", isoCode: "RE"),
new Country(name: "Romania", isoCode: "RO"),
new Country(name: "Serbia", isoCode: "RS"),
new Country(name: "Russian Federation", isoCode: "RU"),
new Country(name: "Rwanda", isoCode: "RW"),
new Country(name: "Saudi Arabia", isoCode: "SA"),
new Country(name: "Solomon Islands", isoCode: "SB"),
new Country(name: "Seychelles", isoCode: "SC"),
new Country(name: "Sudan", isoCode: "SD"),
new Country(name: "Sweden", isoCode: "SE"),
new Country(name: "Singapore", isoCode: "SG"),
new Country(name: "Saint Helena", isoCode: "SH"),
new Country(name: "Slovenia", isoCode: "SI"),
new Country(name: "Svalbard and Jan Mayen", isoCode: "SJ"),
new Country(name: "Slovakia", isoCode: "SK"),
new Country(name: "Sierra Leone", isoCode: "SL"),
new Country(name: "San Marino", isoCode: "SM"),
new Country(name: "Senegal", isoCode: "SN"),
new Country(name: "Somalia", isoCode: "SO"),
new Country(name: "Suriname", isoCode: "SR"),
new Country(name: "South Sudan", isoCode: "SS"),
new Country(name: "Sao Tome and Principe", isoCode: "ST"),
new Country(name: "El Salvador", isoCode: "SV"),
new Country(name: "Sint Maarten", isoCode: "SX"),
new Country(name: "Syrian Arab Republic", isoCode: "SY"),
new Country(name: "Swaziland", isoCode: "SZ"),
new Country(name: "Turks and Caicos Islands", isoCode: "TC"),
new Country(name: "Chad", isoCode: "TD"),
new Country(name: "French Southern Territories", isoCode: "TF"),
new Country(name: "Togo", isoCode: "TG"),
new Country(name: "Thailand", isoCode: "TH"),
new Country(name: "Tajikistan", isoCode: "TJ"),
new Country(name: "Tokelau", isoCode: "TK"),
new Country(name: "Timor-Leste", isoCode: "TL"),
new Country(name: "Turkmenistan", isoCode: "TM"),
new Country(name: "Tunisia", isoCode: "TN"),
new Country(name: "Tonga", isoCode: "TO"),
new Country(name: "Turkey", isoCode: "TR"),
new Country(name: "Trinidad and Tobago", isoCode: "TT"),
new Country(name: "Tuvalu", isoCode: "TV"),
new Country(name: "Taiwan", isoCode: "TW"),
new Country(name: "Tanzania, United Republic of", isoCode: "TZ"),
new Country(name: "Ukraine", isoCode: "UA"),
new Country(name: "Uganda", isoCode: "UG"),
new Country(name: "United States Minor Outlying Islands", isoCode: "UM"),
new Country(name: "United States", isoCode: "US"),
new Country(name: "Uruguay", isoCode: "UY"),
new Country(name: "Uzbekistan", isoCode: "UZ"),
new Country(name: "Holy See (Vatican City State)", isoCode: "VA"),
new Country(name: "Saint Vincent and the Grenadines", isoCode: "VC"),
new Country(name: "Venezuela", isoCode: "VE"),
new Country(name: "Virgin Islands, British", isoCode: "VG"),
new Country(name: "Virgin Islands, U.S.", isoCode: "VI"),
new Country(name: "Vietnam", isoCode: "VN"),
new Country(name: "Vanuatu", isoCode: "VU"),
new Country(name: "Wallis and Futuna", isoCode: "WF"),
new Country(name: "Samoa", isoCode: "WS"),
new Country(name: "Yemen", isoCode: "YE"),
new Country(name: "Mayotte", isoCode: "YT"),
new Country(name: "South Africa", isoCode: "ZA"),
new Country(name: "Zambia", isoCode: "ZM"),
new Country(name: "Zimbabwe", isoCode: "ZW"),
new Country(name: "Other Country", isoCode: "O1"),
];